### ISSUE TITLE
[Enhancement] Command line usage

### ISSUE THREAD

**Issue by TheoCGaming** [idkman2021/BigOuncesAudioEffects#6]
Allow BM to be used in the command line

**Comment by inikishev** [comment]
> Allow BM to be used in the command line

thanks for suggestion ill try

**Comment by inikishev** [comment]
> Allow BM to be used in the command line

I added beatman.py. I haven't used apps in command line  mode so not sure if that is what it is supposed to be. Also I don't know how to actually run it from command line... So I couldn't really test if it works or not, I hope it does.

it should work like this: `beatman -i "path/to/input" -o "path to output" -p "pattern" -s scale -h shift`
or `beatman -input "path/to/input" -output "path to output" -pattern "pattern"` -scale scale -shift shift`

some parameters are optional and it will ask for ones that are necessary if theyre missing

**Comment by TheoCGaming** [comment]
you.... somehow managed to make beatman take a *screenshot*

**Comment by TheoCGaming** [comment]
four of them

**Comment by TheoCGaming** [comment]
oh wait i ran it wrong, py -m

**Comment by inikishev** [comment]
> oh wait i ran it wrong, py -m

how did you make it take a screenshot lmao

**Comment by inikishev** [comment]
uhm I am looking for a job
